name: Common Build & Test

on:
  push:
    branches:
      - master
      - issue/**
      - features/**
      - generic/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, build, and test
        run: |
          cd api-client;
          yarn;
          yarn build;
          yarn test;
        env:
          CI: "true"
